const express = require("express");
const cors = require("cors");
require("dotenv").config();
const app = express();
const port = process.env.PORT;
require("./db/mongoose");
app.use(express.json());
app.use(cors());
const userRouter = require("./routers/users");
const productRouter = require("./routers/product");
const brandRouter = require("./routers/brand");
const offerRouter = require("./routers/offer");
const newsRouter = require("./routers/new");
const favoriteRouter = require("./routers/favorite");
const cardRouter = require("./routers/card");
const imageRouter = require("./routers/productImages");
const feedbackRouter = require("./routers/feedback");
const classificationRouter = require("./routers/classification");
app.use(userRouter);
app.use(productRouter);
app.use(imageRouter);
app.use(brandRouter);
app.use(offerRouter);
app.use(newsRouter);
app.use(cardRouter);
app.use(favoriteRouter);
app.use(feedbackRouter);
app.use(classificationRouter);
app.listen(port, () => {
  console.log("Server is running");
});
